version: 0.2

env:
  variables:
    CI: "true"

phases:
  pre_build:
    runtime-versions:
      nodejs: 16
    commands:
      - yarn
  build:
    runtime-versions:
      nodejs: 16
    commands:
      - cd packages/personal-website
      - yarn install && yarn build
      - cd ../..
      - cd packages/cdk
      - yarn install && yarn build
artifacts:
  base-directory: packages
  files:
    - "cdk/build/**/*"
    - "personal-website/build/**/*"