version: 0.2

env:
  variables:
    CI: "true"

phases:
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - cd packages/personal-website
      - yarn install && yarn build
      - cd ../..
      - cd packages/cdk
      - yarn install && yarn build
artifacts:
  files:
    - "packages/cdk/build/**/*"
    - "packages/personal-website/build/**/*"